# Use this file to test your server-profiles that are pushed to github.
# To use different profiles in this repo, change the SERVER_PROFILE_PATH
# When using your own repo, change the SERVER_PROFILE_URL as well. 

version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess:edge
    command: wait-for pingfederate:9031 -t 420 -- entrypoint.sh start-server
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingaccess
      - VERBOSE=true
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - VERBOSE=true
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - VERBOSE=true
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8080:8080
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
