version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      # **** SERVER PROFILES BEGIN ****
      # Server Profile - Product License
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=layered-profiles/license/pingfederate
      - SERVER_PROFILE_PARENT=EXTENSIONS

      # Server Profile - Extensions
      - SERVER_PROFILE_EXTENSIONS_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_EXTENSIONS_PATH=layered-profiles/extensions/pingfederate
      - SERVER_PROFILE_EXTENSIONS_PARENT=OAUTH

      # Server Profile - OAUTH
      - SERVER_PROFILE_OAUTH_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_OAUTH_PATH=layered-profiles/oauth/pingfederate
      - SERVER_PROFILE_OAUTH_PARENT=GETTING_STARTED
      
      # Base Server Profile
      - SERVER_PROFILE_GETTING_STARTED_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_GETTING_STARTED_PATH=getting-started/pingfederate
      # **** SERVER PROFILE END ****
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

networks:
    pingnet:
